### ISSUE TITLE
JanBan doesn't view any columns

### ISSUE THREAD

**Issue by Lentheon** [janvv/janban-2.0#2]
Hi Jan,

I really like this fork and used it a lot. I used a version before the name was changed to janban. Since a few days, my "Taskboard" Installation shows only columns with no entries. Except I click on refresh in den Outlook Taskboard bar. But even then, I can't move the entries to another column and the option to view only private entries is completely gone.
So I thought to update to the new version janban, but unfortunatly here I don't even see columns.
I think it is a OS patch or security setting, because i didn't change anything at Outlook or the taskboard. Perhaps I am missing something completely :-) Do you have a hint for me or heard of something similiar?

Some Specs from my System. If you need anything further, I am glad to help :-)
Windows 10 Enterprise, Verison 1709, Build 16299.125
Outlook 2016 MSO (16.0.4591.1000) 32 Bit
![2018-01-12 10_03_46-outlook task board - outlook janban](https://user-images.githubusercontent.com/35365228/34867516-4f3ca94e-f778-11e7-8977-2d9634e39dd5.png)
![2018-01-12 10_01_11-outlook task board - outlook kanban](https://user-images.githubusercontent.com/35365228/34867517-4f8c8e8c-f778-11e7-855b-50f798897568.png)

Thank you in advance!
Best regards from Germany,
Benjamin

**Comment by Lentheon** [comment]
Some more information from the the debug html. It says that "angular" is undefined, URL: janban.module.js  
Benjamin

**Comment by janvv** [comment]
Hi Benjamin,
The janban version is still in a very early stage of development. You have to use https://github.com/janvv/outlook-taskboard instead.
The outlook-taskboard version is still maintained and bugs will be fixed. But the source file became too long and the entire application needs to be set up in a more modular way.
I published the JanBan repo only because I do not have private repositories and for others to see how it is progressing. I'll make it more clear in the Readme file that it is still in a unusable state.
